-- SQL Project: Customer Segmentation (RFM Analysis)

create database rfm_project;
use rfm_project;

-- Drop existing tables if any
drop table if exists orders;
drop table if exists orders_clean;
drop table if exists rfm_base;
drop table if exists rfm_scores;
drop table if exists rfm_segments;

-- create orders table
create table orders(
invoice varchar(20),
stock_code varchar(20),
description varchar(100),
quantity int,
invoice_date datetime,
price float,
customer varchar(20),
country varchar(30));
alter table orders
rename column price to unit_price,
rename column customer to customer_id;

-- import data from retail dataset
load data infile "C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/retail.csv"
into table orders
fields terminated by ","
optionally enclosed by '"'
lines terminated by '\r\n'
ignore 1 rows
(invoice, stock_code, description, quantity, @inv_date, unit_price, @cust_id, country)
set
  invoice_date = str_to_date(@inv_date, '%Y-%m-%d %H:%i:%s'),
  customer_id = nullif(@cust_id, '');
 
 create table orders_clean as
 select * from orders
 where customer_id is not null
 and quantity > 0
 and unit_price > 0
 and invoice not like 'C%';
 
 select count(*) from orders_clean;
 
create table rfm_base as
select customer_id,
		datediff('2011-12-31', max(invoice_date)) as recency,
        count(distinct invoice)                   as frequency,
        round(sum(quantity*unit_price),2) 		  as monetary
from orders_clean
group by customer_id;

create table rfm_scores as
select
	customer_id, recency, frequency, monetary,
    NTILE(5) over (order by recency desc) as r_score,
    NTILE(5) over (order by frequency asc) as f_score,
    NTILE(5) over (order by monetary asc) as m_score
from rfm_base;

create table rfm_segments as
select *,
   concat(r_score, f_score, m_score) as rfm_string,
   case
   when r_score >= 4 and f_score >= 4 and m_score >= 4 then "VIP"
   when r_score >= 3 and f_score >= 3				   then "Loyal"
   when r_score >= 4 and f_score <= 2				   then "New Customer"
   when r_score <= 2 and f_score >= 3				   then "At risk"
   when r_score <= 2 and f_score <= 2 and m_score >= 3 then "Big spender gone"
   when r_score = 1									   then "Lost"
   else "Others"
   end as segment
from rfm_scores;

select
	segment,
    count(*) as customers,
    round(avg(recency)) as avg_recency_days,
    round(avg(frequency)) as avg_orders,
    round(avg(monetary),2) as avg_spend
from rfm_segments
group by segment
order by avg_spend desc;

-- Top 10 VIP customers
select
	customer_id, recency, frequency, monetary, rfm_string
from rfm_segments
where segment = "VIP"
order by monetary desc
limit 10;

-- What percentage of total revenue is generated by the top 10% or VIP segment?
select 
    segment,
    count(customer_id) as total_customers,
    round(sum(monetary),2) as total_revenue,
    round((sum(monetary) / (select sum(monetary) from rfm_base)) * 100, 2) as pct_total_revenue
from rfm_segments
where segment = "VIP";

-- What are VIPs buying vs "At Risk" customers?
select 
    s.segment,
    o.description,
    sum(o.quantity) as total_units_bought
from orders_clean o
join rfm_segments s on o.customer_id = s.customer_id
where s.segment in ('VIP', 'At risk')
group by s.segment, o.description
order by total_units_bought desc
limit 10;

-- Which countries hold the highest concentration of VIPs?
select 
    o.country,
    count(distinct s.customer_id) as vip_count,
    round(sum(s.monetary), 2) as total_vip_spend
from rfm_segments s
join orders_clean o on s.customer_id = o.customer_id
where s.segment = 'VIP'
group by o.country
order by total_vip_spend desc
limit 5;
        
        


 

 



    
